# Site settings
title: "Genevieve + Anurag"
description: |
    Orange County, CA

    November 22 & 24, 2019
owner: Anurag Mishra
first_published: 2019
email: wedding@fourd.space
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://genevievewedsanurag.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
